@extends('../layout/' . $layout)

@section('subhead')
    <title>Contract Management - SAMS</title>
@endsection

@section('subcontent')
    <div class="grid grid-cols-12 gap-6">
        <div class="col-span-12 2xl:col-span-12">
            <div class="grid grid-cols-12 gap-6">
                <!-- Header -->
                <div class="col-span-12 mt-4">
                    <div class="intro-y box p-5">
                        <h1 class="text-xl md:text-2xl font-medium flex items-center">
                            <i data-lucide="file-text" class="w-5 h-5 mr-2"></i>
                            Student Assistant Contract Management
                        </h1>
                        <p class="text-slate-500 mt-2">Manage student assistant contracts, renewals, and document storage.</p>
                        <div class="alert alert-info mt-3 flex items-center">
                            <i data-lucide="info" class="w-4 h-4 mr-2"></i>
                            <span class="font-medium">Total Contracts:</span>
                            <span class="ml-2" id="totalContracts">0</span>
                        </div>
                    </div>
                </div>

                <!-- Filters -->
                <div class="col-span-12 intro-y">
                    <div class="box p-5">
                        <h2 class="text-lg font-medium mb-4 flex items-center">
                            <i data-lucide="filter" class="w-5 h-5 mr-2"></i>
                            Filters
                        </h2>
                        <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
                            <div>
                                <label for="searchInput" class="form-label">Search:</label>
                                <input type="text" id="searchInput" class="form-control" placeholder="Search by name or ID" />
                            </div>
                            <div>
                                <label for="officeFilter" class="form-label">Office:</label>
                                <select id="officeFilter" class="form-control">
                                    <option value="">All Offices</option>
                                </select>
                            </div>
                            <div>
                                <label for="statusFilter" class="form-label">Status:</label>
                                <select id="statusFilter" class="form-control">
                                    <option value="">All Statuses</option>
                                    <option value="Active">Active</option>
                                    <option value="Expired">Expired</option>
                                    <option value="Pending">Pending</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Contract Table -->
                <div class="col-span-12 intro-y">
                    <div class="box p-5">
                        <h2 class="text-lg font-medium mb-4 flex items-center">
                            <i data-lucide="clipboard-list" class="w-5 h-5 mr-2"></i>
                            Contract Records
                        </h2>
                        <div class="overflow-x-auto">
                            <table class="table table-report">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Name</th>
                                        <th>Student ID</th>
                                        <th>Office</th>
                                        <th>Start Date</th>
                                        <th>End Date</th>
                                        <th>Status</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody id="contractList">
                                    <tr>
                                        <td colspan="8" class="text-center text-slate-500">Loading...</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="intro-y flex flex-wrap sm:flex-row sm:flex-nowrap items-center mt-3" id="paginationContainer" style="display: none;">
                            <nav class="w-full sm:w-auto sm:mr-auto">
                                <ul class="pagination" id="pagination">
                                    <!-- Pagination items will be generated by JavaScript -->
                                </ul>
                            </nav>
                            <div class="hidden md:block text-slate-500">
                                Showing <span id="paginationStart">0</span> to <span id="paginationEnd">0</span> of <span id="paginationTotal">0</span> entries
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Upload/Add Contract Panel -->
                <div class="col-span-12 intro-y" id="uploadPanel" style="display: none;">
                    <div class="box p-5">
                        <h2 class="text-lg font-medium mb-4 flex items-center">
                            <i data-lucide="upload" class="w-5 h-5 mr-2"></i>
                            Upload / Renew Contract
                        </h2>
                        
                        <form id="uploadForm" class="grid grid-cols-12 gap-4">
                            <div class="col-span-12 md:col-span-6">
                                <label for="studentSelect" class="form-label">Student Assistant: <span class="text-danger">*</span></label>
                                <select id="studentSelect" name="studentSelect" class="form-control" required>
                                    <option value="">Select Student Assistant...</option>
                                </select>
                            </div>
                            <div class="col-span-12 md:col-span-6">
                                <label for="uploadOffice" class="form-label">Office:</label>
                                <input type="text" id="uploadOffice" name="uploadOffice" class="form-control" readonly style="background-color: #f3f4f6; cursor: not-allowed;" />
                            </div>
                            <div class="col-span-12 md:col-span-6">
                                <label for="uploadID" class="form-label">Student ID:</label>
                                <input type="text" id="uploadID" name="uploadID" class="form-control" readonly style="background-color: #f3f4f6; cursor: not-allowed;" />
                            </div>
                            <div class="col-span-12 md:col-span-6">
                                <label for="uploadName" class="form-label">Full Name:</label>
                                <input type="text" id="uploadName" name="uploadName" class="form-control" readonly style="background-color: #f3f4f6; cursor: not-allowed;" />
                            </div>
                            <div class="col-span-12 md:col-span-6">
                                <label for="startDate" class="form-label">Start Date:</label>
                                <input type="date" id="startDate" name="startDate" class="form-control" required />
                            </div>
                            <div class="col-span-12 md:col-span-6">
                                <label for="endDate" class="form-label">End Date:</label>
                                <input type="date" id="endDate" name="endDate" class="form-control" required />
                            </div>
                            <div class="col-span-12">
                                <label for="pdfUpload" class="form-label">Upload Contract PDF (Optional):</label>
                                <input type="file" id="pdfUpload" name="pdfUpload" class="form-control" accept="application/pdf" />
                                <div class="text-xs text-slate-500 mt-1">Only PDF files are accepted. Maximum file size: 10MB</div>
                            </div>
                            <div class="col-span-12">
                                <button type="submit" class="btn btn-primary">
                                    <i data-lucide="save" class="w-4 h-4 mr-2"></i>
                                    Save Contract
                                </button>
                                <button type="button" id="cancelUploadBtn" class="btn btn-secondary ml-2">
                                    <i data-lucide="x" class="w-4 h-4 mr-2"></i>
                                    Cancel
                                </button>
                            </div>
                        </form>
                        <div id="message" class="mt-3"></div>
                    </div>
                </div>

                <!-- Contract Details Panel -->
                <div class="col-span-12 intro-y" id="contractDetailsPanel" style="display: none;">
                    <div class="box p-5">
                        <h2 class="text-lg font-medium mb-4 flex items-center">
                            <i data-lucide="file-text" class="w-5 h-5 mr-2"></i>
                            Contract Details
                        </h2>
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                            <div>
                                <span class="font-medium text-slate-600">Student Name:</span>
                                <span id="detailName" class="text-slate-800"></span>
                            </div>
                            <div>
                                <span class="font-medium text-slate-600">Student ID:</span>
                                <span id="detailStudentId" class="text-slate-800"></span>
                            </div>
                            <div>
                                <span class="font-medium text-slate-600">Office:</span>
                                <span id="detailOffice" class="text-slate-800"></span>
                            </div>
                            <div>
                                <span class="font-medium text-slate-600">Start Date:</span>
                                <span id="detailStartDate" class="text-slate-800"></span>
                            </div>
                            <div>
                                <span class="font-medium text-slate-600">End Date:</span>
                                <span id="detailEndDate" class="text-slate-800"></span>
                            </div>
                            <div>
                                <span class="font-medium text-slate-600">Status:</span>
                                <span id="detailStatus" class="text-slate-800"></span>
                            </div>
                            <div>
                                <span class="font-medium text-slate-600">Uploaded Date:</span>
                                <span id="detailUploadDate" class="text-slate-800"></span>
                            </div>
                        </div>
                        <div class="flex gap-2">
                            <button class="btn btn-primary" onclick="downloadContract()">
                                <i data-lucide="download" class="w-4 h-4 mr-2"></i>
                                Download PDF
                            </button>
                            <button class="btn btn-warning" onclick="editContract()">
                                <i data-lucide="edit" class="w-4 h-4 mr-2"></i>
                                Edit Contract
                            </button>
                            <button class="btn btn-danger" onclick="deleteContract()">
                                <i data-lucide="trash-2" class="w-4 h-4 mr-2"></i>
                                Delete
                            </button>
                            <button class="btn btn-secondary" onclick="closeContractPanel()">
                                <i data-lucide="x" class="w-4 h-4 mr-2"></i>
                                Close
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script type="module">
        (function () {
            let contractData = [];
            let filteredData = [];
            let currentContractId = null;
            let studentAssistantsList = [];
            let officesList = [];
            let isEditMode = false;
            let currentPage = 1;
            const itemsPerPage = 10;

            // DOM elements
            const searchInput = document.getElementById('searchInput');
            const officeFilter = document.getElementById('officeFilter');
            const statusFilter = document.getElementById('statusFilter');
            const contractList = document.getElementById('contractList');
            const uploadPanel = document.getElementById('uploadPanel');
            const toggleUploadPanel = document.getElementById('toggleUploadPanel');
            const cancelUploadBtn = document.getElementById('cancelUploadBtn');
            const uploadForm = document.getElementById('uploadForm');
            const contractDetailsPanel = document.getElementById('contractDetailsPanel');
            const totalContracts = document.getElementById('totalContracts');
            const messageDiv = document.getElementById('message');

            // Initialize page
            async function init() {
                await Promise.all([loadOffices(), loadStudentAssistants(), loadContracts()]);
                setupEventListeners();
                setDefaultDates();
            }

            // Load offices from API
            async function loadOffices() {
                try {
                    const response = await fetch('/api/offices');
                    const result = await response.json();
                    
                    if (result.success) {
                        officesList = result.data.filter(o => o.is_active);
                        const officeFilter = document.getElementById('officeFilter');
                        officeFilter.innerHTML = '<option value="">All Offices</option>' + 
                            officesList.map(office => `<option value="${office.name}">${office.name}</option>`).join('');
                    }
                } catch (error) {
                    console.error('Error loading offices:', error);
                }
            }

            // Load student assistants for dropdown
            async function loadStudentAssistants() {
                try {
                    const response = await fetch('/api/sa-accounts');
                    const result = await response.json();
                    
                    if (result.success) {
                        studentAssistantsList = result.data;
                        const studentSelect = document.getElementById('studentSelect');
                        studentSelect.innerHTML = '<option value="">Select Student Assistant...</option>' + 
                            studentAssistantsList.map(sa => {
                                const fullName = sa.full_name || sa.name || 'Unknown';
                                const studentId = sa.student_id_number || '';
                                return `<option value="${sa.student_id_number}" data-name="${fullName}" data-office="${sa.office || ''}">${fullName} (${studentId})</option>`;
                            }).join('');
                    }
                } catch (error) {
                    console.error('Error loading student assistants:', error);
                }
            }

            // Load contracts from API
            async function loadContracts() {
                try {
                    const response = await fetch('/api/contracts');
                    const result = await response.json();
                    
                    if (result.success) {
                        contractData = result.data;
                        filteredData = [...contractData];
                        updateTotalCount();
                        renderTable();
                    } else {
                        showMessage('Failed to load contracts', 'error');
                        contractList.innerHTML = '<tr><td colspan="8" class="text-center text-slate-500">Error loading contracts</td></tr>';
                    }
                } catch (error) {
                    console.error('Error loading contracts:', error);
                    showMessage('An error occurred while loading contracts', 'error');
                    contractList.innerHTML = '<tr><td colspan="8" class="text-center text-slate-500">Error loading contracts</td></tr>';
                }
            }

            // Setup event listeners
            function setupEventListeners() {
                searchInput.addEventListener('input', filterData);
                officeFilter.addEventListener('change', filterData);
                statusFilter.addEventListener('change', filterData);
                toggleUploadPanel.addEventListener('click', toggleUpload);
                cancelUploadBtn.addEventListener('click', hideUpload);
                uploadForm.addEventListener('submit', handleFormSubmit);
                
                // Student selection change
                document.getElementById('studentSelect').addEventListener('change', function() {
                    const selectedOption = this.options[this.selectedIndex];
                    if (selectedOption && selectedOption.value) {
                        document.getElementById('uploadID').value = selectedOption.value;
                        document.getElementById('uploadName').value = selectedOption.dataset.name || '';
                        document.getElementById('uploadOffice').value = selectedOption.dataset.office || '';
                    } else {
                        document.getElementById('uploadID').value = '';
                        document.getElementById('uploadName').value = '';
                        document.getElementById('uploadOffice').value = '';
                    }
                });
                
                // Date validation
                document.getElementById('startDate').addEventListener('change', validateDates);
                document.getElementById('endDate').addEventListener('change', validateDates);
            }

            // Set default dates
            function setDefaultDates() {
                const today = new Date();
                const nextMonth = new Date(today.getFullYear(), today.getMonth() + 1, today.getDate());
                const sixMonthsLater = new Date(today.getFullYear(), today.getMonth() + 6, today.getDate());
                
                document.getElementById('startDate').value = today.toISOString().split('T')[0];
                document.getElementById('endDate').value = sixMonthsLater.toISOString().split('T')[0];
            }

            // Validate dates
            function validateDates() {
                const startDate = new Date(document.getElementById('startDate').value);
                const endDate = new Date(document.getElementById('endDate').value);
                
                if (endDate <= startDate) {
                    document.getElementById('endDate').setCustomValidity('End date must be after start date');
                } else {
                    document.getElementById('endDate').setCustomValidity('');
                }
            }

            // Filter data based on search and filters
            function filterData() {
                const searchTerm = searchInput.value.toLowerCase();
                const selectedOffice = officeFilter.value;
                const selectedStatus = statusFilter.value;

                filteredData = contractData.filter(contract => {
                    const matchesSearch = !searchTerm || 
                        contract.name.toLowerCase().includes(searchTerm) || 
                        contract.studentId.toLowerCase().includes(searchTerm);
                    
                    const matchesOffice = !selectedOffice || contract.office === selectedOffice;
                    const matchesStatus = !selectedStatus || contract.status === selectedStatus;

                    return matchesSearch && matchesOffice && matchesStatus;
                });

                // Reset to first page when filtering
                currentPage = 1;
                renderTable();
            }

            // Render the contract table with pagination
            function renderTable() {
                if (filteredData.length === 0) {
                    contractList.innerHTML = '<tr><td colspan="8" class="text-center text-slate-500">No contract records found</td></tr>';
                    document.getElementById('paginationContainer').style.display = 'none';
                    return;
                }

                // Calculate pagination
                const totalPages = Math.ceil(filteredData.length / itemsPerPage);
                const startIndex = (currentPage - 1) * itemsPerPage;
                const endIndex = Math.min(startIndex + itemsPerPage, filteredData.length);
                const paginatedData = filteredData.slice(startIndex, endIndex);

                // Render table rows
                contractList.innerHTML = paginatedData.map((contract, index) => {
                    const globalIndex = startIndex + index + 1;
                    return `
                        <tr>
                            <td>${globalIndex}</td>
                            <td>${contract.name}</td>
                            <td>${contract.studentId}</td>
                            <td>${contract.office}</td>
                            <td>${formatDate(contract.startDate)}</td>
                            <td>${formatDate(contract.endDate)}</td>
                            <td><span class="badge ${getStatusBadgeClass(contract.status)} text-white rounded p-1">${contract.status}</span></td>
                            <td>
                                <button class="btn btn-primary btn-sm text-white" onclick="viewContract(${contract.id})">
                                    <i data-lucide="eye" class="w-4 h-4 mr-1"></i>
                                    View
                                </button>
                            </td>
                        </tr>
                    `;
                }).join('');

                // Update pagination info
                document.getElementById('paginationStart').textContent = filteredData.length > 0 ? startIndex + 1 : 0;
                document.getElementById('paginationEnd').textContent = endIndex;
                document.getElementById('paginationTotal').textContent = filteredData.length;

                // Render pagination controls
                renderPagination(totalPages);
                
                // Show pagination container
                document.getElementById('paginationContainer').style.display = 'flex';
                
                reloadLucideIcons();
            }

            // Render pagination controls
            function renderPagination(totalPages) {
                const paginationEl = document.getElementById('pagination');
                
                if (totalPages <= 1) {
                    paginationEl.innerHTML = '';
                    document.getElementById('paginationContainer').style.display = 'none';
                    return;
                }

                let paginationHTML = '';

                // First page button
                paginationHTML += `
                    <li class="page-item ${currentPage === 1 ? 'disabled' : ''}">
                        <a class="page-link" href="#" onclick="goToPage(1); return false;">
                            <i class="w-4 h-4" data-lucide="chevrons-left"></i>
                        </a>
                    </li>
                `;

                // Previous page button
                paginationHTML += `
                    <li class="page-item ${currentPage === 1 ? 'disabled' : ''}">
                        <a class="page-link" href="#" onclick="goToPage(${currentPage - 1}); return false;">
                            <i class="w-4 h-4" data-lucide="chevron-left"></i>
                        </a>
                    </li>
                `;

                // Page numbers
                let startPage = Math.max(1, currentPage - 2);
                let endPage = Math.min(totalPages, currentPage + 2);

                if (startPage > 1) {
                    paginationHTML += `<li class="page-item"><a class="page-link" href="#" onclick="goToPage(1); return false;">1</a></li>`;
                    if (startPage > 2) {
                        paginationHTML += `<li class="page-item"><a class="page-link" href="#">...</a></li>`;
                    }
                }

                for (let i = startPage; i <= endPage; i++) {
                    paginationHTML += `
                        <li class="page-item ${i === currentPage ? 'active' : ''}">
                            <a class="page-link" href="#" onclick="goToPage(${i}); return false;">${i}</a>
                        </li>
                    `;
                }

                if (endPage < totalPages) {
                    if (endPage < totalPages - 1) {
                        paginationHTML += `<li class="page-item"><a class="page-link" href="#">...</a></li>`;
                    }
                    paginationHTML += `<li class="page-item"><a class="page-link" href="#" onclick="goToPage(${totalPages}); return false;">${totalPages}</a></li>`;
                }

                // Next page button
                paginationHTML += `
                    <li class="page-item ${currentPage === totalPages ? 'disabled' : ''}">
                        <a class="page-link" href="#" onclick="goToPage(${currentPage + 1}); return false;">
                            <i class="w-4 h-4" data-lucide="chevron-right"></i>
                        </a>
                    </li>
                `;

                // Last page button
                paginationHTML += `
                    <li class="page-item ${currentPage === totalPages ? 'disabled' : ''}">
                        <a class="page-link" href="#" onclick="goToPage(${totalPages}); return false;">
                            <i class="w-4 h-4" data-lucide="chevrons-right"></i>
                        </a>
                    </li>
                `;

                paginationEl.innerHTML = paginationHTML;
                reloadLucideIcons();
            }

            // Go to specific page
            window.goToPage = function(page) {
                const totalPages = Math.ceil(filteredData.length / itemsPerPage);
                if (page < 1 || page > totalPages || page === currentPage) {
                    return;
                }
                currentPage = page;
                renderTable();
                // Scroll to top of table
                document.querySelector('.table').scrollIntoView({ behavior: 'smooth', block: 'start' });
            };

            // Get status badge class
            function getStatusBadgeClass(status) {
                switch (status) {
                    case 'Active': return 'bg-success text-white';
                    case 'Expired': return 'bg-danger text-white';
                    case 'Pending': return 'bg-warning text-white';
                    default: return 'bg-secondary text-white';
                }
            }

            // Format date for display
            function formatDate(dateString) {
                const date = new Date(dateString);
                return date.toLocaleDateString('en-US', {
                    year: 'numeric',
                    month: 'short',
                    day: 'numeric'
                });
            }

            // Update total count
            function updateTotalCount() {
                totalContracts.textContent = contractData.length;
            }

            // Toggle upload panel visibility
            function toggleUpload() {
                if (uploadPanel.style.display === 'none') {
                    showUpload();
                } else {
                    hideUpload();
                }
            }

            // Show upload panel
            function showUpload() {
                uploadPanel.style.display = 'block';
                toggleUploadPanel.innerHTML = '<i data-lucide="minus" class="w-4 h-4 mr-2"></i>Hide Form';
                uploadPanel.scrollIntoView({ behavior: 'smooth' });
            }

            // Hide upload panel
            function hideUpload() {
                uploadPanel.style.display = 'none';
                toggleUploadPanel.innerHTML = '<i data-lucide="plus" class="w-4 h-4 mr-2"></i>Add Contract';
                uploadForm.reset();
                document.getElementById('studentSelect').disabled = false;
                isEditMode = false;
                currentContractId = null;
                setDefaultDates();
                messageDiv.innerHTML = '';
                reloadLucideIcons();
            }

            // Handle form submission
            async function handleFormSubmit(e) {
                e.preventDefault();
                
                const formData = new FormData(uploadForm);
                const studentId = formData.get('studentSelect');
                
                if (!studentId) {
                    showMessage('Please select a student assistant', 'error');
                    return;
                }
                
                // Create FormData for API
                const apiFormData = new FormData();
                apiFormData.append('studentId', studentId);
                apiFormData.append('startDate', formData.get('startDate'));
                apiFormData.append('endDate', formData.get('endDate'));
                
                const fileInput = document.getElementById('pdfUpload');
                if (fileInput.files[0]) {
                    apiFormData.append('pdfUpload', fileInput.files[0]);
                }
                
                try {
                    const response = await fetch('/contract-management/upload', {
                        method: 'POST',
                        headers: {
                            'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
                        },
                        body: apiFormData
                    });
                    
                    const result = await response.json();
                    
                    if (response.ok) {
                        await loadContracts();
                        hideUpload();
                        showMessage(result.message || 'Contract updated successfully!', 'success');
                    } else {
                        showMessage(result.message || 'Failed to update contract', 'error');
                    }
                } catch (error) {
                    console.error('Error updating contract:', error);
                    showMessage('An error occurred while updating contract', 'error');
                }
            }

            // View contract function (global scope for onclick)
            window.viewContract = function(contractId) {
                const contract = contractData.find(c => c.id === contractId);
                if (!contract) return;

                currentContractId = contractId;
                
                // Populate details
                document.getElementById('detailName').textContent = contract.name;
                document.getElementById('detailStudentId').textContent = contract.studentId;
                document.getElementById('detailOffice').textContent = contract.office;
                document.getElementById('detailStartDate').textContent = formatDate(contract.startDate);
                document.getElementById('detailEndDate').textContent = formatDate(contract.endDate);
                document.getElementById('detailStatus').innerHTML = `<span class="badge ${getStatusBadgeClass(contract.status)} text-white rounded p-1">${contract.status}</span>`;
                document.getElementById('detailUploadDate').textContent = formatDate(contract.uploadDate);

                // Show panel
                contractDetailsPanel.style.display = 'block';
                contractDetailsPanel.scrollIntoView({ behavior: 'smooth' });
                reloadLucideIcons();
            };

            // Close contract panel function (global scope for onclick)
            window.closeContractPanel = function() {
                contractDetailsPanel.style.display = 'none';
                currentContractId = null;
            };

            // Download contract function (global scope for onclick)
            window.downloadContract = function() {
                if (!currentContractId) return;
                
                const contract = contractData.find(c => c.id === currentContractId);
                if (contract && contract.filePath) {
                    // In real implementation, this would download the actual PDF
                    window.open(contract.filePath, '_blank');
                } else {
                    showMessage('No contract PDF file available for download', 'info');
                }
            };

            // Edit contract function (global scope for onclick)
            window.editContract = function() {
                if (!currentContractId) return;
                
                const contract = contractData.find(c => c.id === currentContractId);
                if (!contract) return;
                
                // Find student assistant
                const sa = studentAssistantsList.find(s => s.student_id_number === contract.studentId);
                if (!sa) {
                    showMessage('Student assistant not found', 'error');
                    return;
                }
                
                // Populate form
                document.getElementById('studentSelect').value = contract.studentId;
                document.getElementById('uploadID').value = contract.studentId;
                document.getElementById('uploadName').value = contract.name;
                document.getElementById('uploadOffice').value = contract.office;
                document.getElementById('startDate').value = contract.startDate;
                document.getElementById('endDate').value = contract.endDate;
                
                // Disable student selection in edit mode
                document.getElementById('studentSelect').disabled = true;
                
                isEditMode = true;
                currentContractId = contract.id;
                
                // Show form and hide details panel
                contractDetailsPanel.style.display = 'none';
                showUpload();
            };

            // Delete contract function (global scope for onclick)
            window.deleteContract = async function() {
                if (!currentContractId) return;
                
                if (!confirm('Are you sure you want to delete this contract? This will remove the contract dates from the student assistant.')) {
                    return;
                }
                
                const contract = contractData.find(c => c.id === currentContractId);
                if (!contract) return;
                
                try {
                    // Find student assistant and clear contract dates
                    const sa = studentAssistantsList.find(s => s.student_id_number === contract.studentId);
                    if (!sa) {
                        showMessage('Student assistant not found', 'error');
                        return;
                    }
                    
                    const response = await fetch(`/api/sa-accounts/${sa.id}`, {
                        method: 'PUT',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
                        },
                        body: JSON.stringify({
                            name: sa.name,
                            full_name: sa.full_name,
                            student_id_number: sa.student_id_number,
                            email: sa.email,
                            office: sa.office,
                            contact: sa.contact,
                            gender: sa.gender,
                            status: sa.status,
                            active: sa.active,
                            contract_start_date: null,
                            contract_end_date: null
                        })
                    });
                    
                    const result = await response.json();
                    
                    if (response.ok) {
                        await loadContracts();
                        closeContractPanel();
                        showMessage('Contract deleted successfully!', 'success');
                    } else {
                        showMessage(result.message || 'Failed to delete contract', 'error');
                    }
                } catch (error) {
                    console.error('Error deleting contract:', error);
                    showMessage('An error occurred while deleting contract', 'error');
                }
            };

            // Show message function
            function showMessage(message, type) {
                messageDiv.innerHTML = `
                    <div class="alert alert-${type === 'success' ? 'success' : type === 'error' ? 'danger' : 'info'} flex items-center">
                        <i data-lucide="${type === 'success' ? 'check-circle' : type === 'error' ? 'alert-circle' : 'info'}" class="w-4 h-4 mr-2"></i>
                        ${message}
                    </div>
                `;
                
                reloadLucideIcons();
                
                // Hide message after 5 seconds
                setTimeout(() => {
                    messageDiv.innerHTML = '';
                }, 5000);
            }

            // Reload Lucide icons
            function reloadLucideIcons() {
                if (window.lucide && window.lucide.createIcons) {
                    window.lucide.createIcons({
                        icons: window.lucide.icons,
                        "stroke-width": 1.5,
                        nameAttr: "data-lucide",
                    });
                }
            }

            // Initialize when DOM is loaded
            document.addEventListener('DOMContentLoaded', init);
        })();
    </script>
@endsection
