@extends('../layout/' . $layout)

@section('subhead')
    <title>Office Head Account Management - SAMS</title>
@endsection

@section('subcontent')
    <div class="grid grid-cols-12 gap-6">
        <div class="col-span-12 2xl:col-span-12">
            <div class="grid grid-cols-12 gap-6">
                <!-- Header -->
                <div class="col-span-12 mt-4">
                    <div class="intro-y box p-5">
                        <h1 class="text-xl md:text-2xl font-medium flex items-center">
                            <i data-lucide="user-cog" class="w-5 h-5 mr-2"></i>
                            Office Head Account Management
                        </h1>
                        <p class="text-slate-500 mt-2">Manage office head accounts, profiles, and access permissions.</p>
                        <div class="alert alert-info mt-3 flex items-center">
                            <i data-lucide="info" class="w-4 h-4 mr-2"></i>
                            <span class="font-medium">Total Office Heads:</span>
                            <span class="ml-2" id="totalCount">0</span>
                        </div>
                    </div>
                </div>

                <!-- Filters -->
                <div class="col-span-12 intro-y">
                    <div class="box p-5">
                        <h2 class="text-lg font-medium mb-4 flex items-center">
                            <i data-lucide="filter" class="w-5 h-5 mr-2"></i>
                            Filters
                        </h2>
                        <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
                            <div>
                                <label for="searchInput" class="form-label">Search:</label>
                                <input type="text" id="searchInput" class="form-control" placeholder="Search by name or email" />
                            </div>
                            <div>
                                <label for="officeFilter" class="form-label">Office:</label>
                                <select id="officeFilter" class="form-control">
                                    <option value="">All Offices</option>
                                </select>
                            </div>
                            <div>
                                <label for="statusFilter" class="form-label">Status:</label>
                                <select id="statusFilter" class="form-control">
                                    <option value="">All Status</option>
                                    <option value="active">Active</option>
                                    <option value="inactive">Inactive</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Office Heads Table -->
                <div class="col-span-12 intro-y">
                    <div class="box p-5">
                        <h2 class="text-lg font-medium mb-4 flex items-center">
                            <i data-lucide="clipboard-list" class="w-5 h-5 mr-2"></i>
                            Office Head Accounts
                        </h2>
                        <div class="overflow-x-auto">
                            <table class="table table-report">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Office</th>
                                        <th>Contact</th>
                                        <th>Status</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody id="officeHeadTableBody">
                                    <tr>
                                        <td colspan="7" class="text-center text-slate-500">Loading...</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="intro-y flex flex-wrap sm:flex-row sm:flex-nowrap items-center mt-3" id="paginationContainer" style="display: none;">
                            <nav class="w-full sm:w-auto sm:mr-auto">
                                <ul class="pagination" id="pagination">
                                    <!-- Pagination items will be generated by JavaScript -->
                                </ul>
                            </nav>
                            <div class="hidden md:block text-slate-500">
                                Showing <span id="paginationStart">0</span> to <span id="paginationEnd">0</span> of <span id="paginationTotal">0</span> entries
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Add Office Head Section -->
                <div class="col-span-12 intro-y">
                    <div class="box p-5">
                        <div class="flex items-center justify-between mb-4">
                            <h2 class="text-lg font-medium flex items-center mr-auto">
                                <i data-lucide="user-plus" class="w-5 h-5 mr-2"></i>
                                Add New Office Head
                            </h2>
                        </div>
                        
                        <div class="add-form" id="addForm" style="display: none;">
                            <form id="officeHeadForm" class="grid grid-cols-12 gap-4">
                                <div class="col-span-12 md:col-span-6">
                                    <label for="name" class="form-label">Nickname: <span class="text-danger">*</span></label>
                                    <input type="text" id="name" name="name" class="form-control" required />
                                </div>
                                <div class="col-span-12 md:col-span-6">
                                    <label for="full_name" class="form-label">Full Name: <span class="text-danger">*</span></label>
                                    <input type="text" id="full_name" name="full_name" class="form-control" required />
                                </div>
                                <div class="col-span-12 md:col-span-6">
                                    <label for="email" class="form-label">Email: <span class="text-danger">*</span></label>
                                    <input type="email" id="email" name="email" class="form-control" required />
                                </div>
                                <div class="col-span-12 md:col-span-6">
                                    <label for="password" class="form-label">Password: <span class="text-danger">*</span></label>
                                    <input type="password" id="password" name="password" class="form-control" required minlength="8" />
                                </div>
                                <div class="col-span-12 md:col-span-6">
                                    <label for="office" class="form-label">Office: <span class="text-danger">*</span></label>
                                    <select id="office" name="office" class="form-control" required>
                                        <option value="">Select Office</option>
                                    </select>
                                </div>
                                <div class="col-span-12 md:col-span-6">
                                    <label for="contact" class="form-label">Contact Number:</label>
                                    <input type="text" id="contact" name="contact" class="form-control" placeholder="09XXXXXXXXX" pattern="^09\d{9}$" />
                                </div>
                                <div class="col-span-12 md:col-span-6">
                                    <label for="gender" class="form-label">Gender: <span class="text-danger">*</span></label>
                                    <select id="gender" name="gender" class="form-control" required>
                                        <option value="">Select Gender</option>
                                        <option value="male">Male</option>
                                        <option value="female">Female</option>
                                        <option value="other">Other</option>
                                    </select>
                                </div>
                                <div class="col-span-12 md:col-span-6">
                                    <label for="active" class="form-label">Status:</label>
                                    <select id="active" name="active" class="form-control">
                                        <option value="1">Active</option>
                                        <option value="0">Inactive</option>
                                    </select>
                                </div>
                                <div class="col-span-12">
                                    <button type="submit" class="btn btn-primary">
                                        <i data-lucide="save" class="w-4 h-4 mr-2"></i>
                                        Save Office Head
                                    </button>
                                    <button type="button" id="cancelFormBtn" class="btn btn-secondary ml-2">
                                        <i data-lucide="x" class="w-4 h-4 mr-2 text-black"></i>
                                        Cancel
                                    </button>
                                </div>
                            </form>
                        </div>
                        <div id="message" class="mt-3"></div>
                    </div>
                </div>

                <!-- Office Head Details Panel -->
                <div class="col-span-12 intro-y" id="officeHeadDetailsPanel" style="display: none;">
                    <div class="box p-5">
                        <h2 class="text-lg font-medium mb-4 flex items-center">
                            <i data-lucide="user" class="w-5 h-5 mr-2"></i>
                            Office Head Details
                        </h2>
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                            <div>
                                <span class="font-medium text-slate-600">Name:</span>
                                <span id="detailName" class="text-slate-800"></span>
                            </div>
                            <div>
                                <span class="font-medium text-slate-600">Full Name:</span>
                                <span id="detailFullName" class="text-slate-800"></span>
                            </div>
                            <div>
                                <span class="font-medium text-slate-600">Email:</span>
                                <span id="detailEmail" class="text-slate-800"></span>
                            </div>
                            <div>
                                <span class="font-medium text-slate-600">Office:</span>
                                <span id="detailOffice" class="text-slate-800"></span>
                            </div>
                            <div>
                                <span class="font-medium text-slate-600">Contact:</span>
                                <span id="detailContact" class="text-slate-800"></span>
                            </div>
                            <div>
                                <span class="font-medium text-slate-600">Gender:</span>
                                <span id="detailGender" class="text-slate-800"></span>
                            </div>
                            <div>
                                <span class="font-medium text-slate-600">Status:</span>
                                <span id="detailStatus" class="text-slate-800"></span>
                            </div>
                        </div>
                        <div class="flex gap-2">
                            <button class="btn btn-primary" onclick="editOfficeHead()">
                                <i data-lucide="edit" class="w-4 h-4 mr-2"></i>
                                Edit
                            </button>
                            <button class="btn btn-danger" onclick="deleteOfficeHead()">
                                <i data-lucide="trash-2" class="w-4 h-4 mr-2"></i>
                                Delete
                            </button>
                            <button class="btn btn-secondary" onclick="closeOfficeHeadPanel()">
                                <i data-lucide="x" class="w-4 h-4 mr-2"></i>
                                Close
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script type="module">
        (function () {
            let officeHeadsData = [];
            let filteredData = [];
            let officesData = [];
            let currentOfficeHeadId = null;
            let isEditMode = false;
            let currentPage = 1;
            const itemsPerPage = 10;

            // DOM elements
            const searchInput = document.getElementById('searchInput');
            const officeFilter = document.getElementById('officeFilter');
            const statusFilter = document.getElementById('statusFilter');
            const officeHeadTableBody = document.getElementById('officeHeadTableBody');
            const addForm = document.getElementById('addForm');
            const toggleFormBtn = document.getElementById('toggleFormBtn');
            const cancelFormBtn = document.getElementById('cancelFormBtn');
            const officeHeadForm = document.getElementById('officeHeadForm');
            const officeHeadDetailsPanel = document.getElementById('officeHeadDetailsPanel');
            const totalCount = document.getElementById('totalCount');
            const messageDiv = document.getElementById('message');
            const officeSelect = document.getElementById('office');

            // Helper function to re-initialize Lucide icons
            function reloadLucideIcons() {
                if (window.lucide && window.lucide.createIcons) {
                    window.lucide.createIcons({
                        icons: window.lucide.icons,
                        "stroke-width": 1.5,
                        nameAttr: "data-lucide",
                    });
                }
            }

            // Initialize page
            async function init() {
                await Promise.all([loadOffices(), loadOfficeHeads()]);
                setupEventListeners();
                setupOfficeUpdateListener();
            }

            // Listen for office updates from other tabs/pages
            function setupOfficeUpdateListener() {
                // Use BroadcastChannel for cross-tab communication
                if (typeof BroadcastChannel !== 'undefined') {
                    const channel = new BroadcastChannel('office-updates');
                    channel.addEventListener('message', (event) => {
                        if (event.data.type === 'office-updated' || event.data.type === 'office-created' || event.data.type === 'office-deleted') {
                            // Reload offices when office is updated, created, or deleted
                            loadOffices();
                            // Also reload office heads to update office names in the table
                            loadOfficeHeads();
                        }
                    });
                }
                
                // Also refresh when window regains focus (fallback)
                window.addEventListener('focus', () => {
                    loadOffices();
                });
            }

            // Load offices for dropdown
            async function loadOffices() {
                try {
                    const response = await fetch('/api/offices');
                    const result = await response.json();
                    
                    if (result.success) {
                        officesData = result.data.filter(o => o.is_active);
                        updateOfficeSelect();
                        
                        // Populate office filter (show all offices for filtering)
                        officeFilter.innerHTML = '<option value="">All Offices</option>' + 
                            officesData.map(office => `<option value="${office.name}">${office.name}</option>`).join('');
                    }
                } catch (error) {
                    console.error('Error loading offices:', error);
                }
            }

            // Update office select dropdown (filter out offices with existing office heads)
            function updateOfficeSelect() {
                // Get offices that already have an office head assigned
                const assignedOffices = new Set(
                    officeHeadsData
                        .filter(oh => oh.office && oh.active) // Only count active office heads
                        .map(oh => oh.office)
                );
                
                // Filter out offices that already have an office head (unless we're in edit mode)
                const availableOffices = isEditMode 
                    ? officesData // Show all offices when editing
                    : officesData.filter(office => !assignedOffices.has(office.name));
                
                officeSelect.innerHTML = '<option value="">Select Office</option>' + 
                    availableOffices.map(office => `<option value="${office.name}">${office.name}</option>`).join('');
            }

            // Load office heads from API
            async function loadOfficeHeads() {
                try {
                    const response = await fetch('/api/officeheads');
                    const result = await response.json();
                    
                    if (result.success) {
                        officeHeadsData = result.data;
                        filteredData = [...officeHeadsData];
                        updateTotalCount();
                        renderTable();
                        // Update office select after loading office heads
                        updateOfficeSelect();
                    } else {
                        showMessage('Failed to load office heads', 'error');
                    }
                } catch (error) {
                    console.error('Error loading office heads:', error);
                    showMessage('An error occurred while loading office heads', 'error');
                    officeHeadTableBody.innerHTML = '<tr><td colspan="7" class="text-center text-slate-500">Error loading office heads</td></tr>';
                }
            }

            // Setup event listeners
            function setupEventListeners() {
                searchInput.addEventListener('input', filterData);
                officeFilter.addEventListener('change', filterData);
                statusFilter.addEventListener('change', filterData);
                toggleFormBtn.addEventListener('click', toggleForm);
                cancelFormBtn.addEventListener('click', hideForm);
                officeHeadForm.addEventListener('submit', handleFormSubmit);
            }

            // Filter data
            function filterData() {
                const searchTerm = searchInput.value.toLowerCase();
                const selectedOffice = officeFilter.value;
                const selectedStatus = statusFilter.value;

                filteredData = officeHeadsData.filter(oh => {
                    const matchesSearch = !searchTerm || 
                        oh.name.toLowerCase().includes(searchTerm) || 
                        oh.email.toLowerCase().includes(searchTerm);
                    
                    const matchesOffice = !selectedOffice || oh.office === selectedOffice;
                    
                    const matchesStatus = !selectedStatus || 
                        (selectedStatus === 'active' && oh.active) ||
                        (selectedStatus === 'inactive' && !oh.active);

                    return matchesSearch && matchesOffice && matchesStatus;
                });

                // Reset to first page when filtering
                currentPage = 1;
                renderTable();
            }

            // Render table with pagination
            function renderTable() {
                if (filteredData.length === 0) {
                    officeHeadTableBody.innerHTML = '<tr><td colspan="7" class="text-center text-slate-500">No office heads found</td></tr>';
                    document.getElementById('paginationContainer').style.display = 'none';
                    return;
                }

                // Calculate pagination
                const totalPages = Math.ceil(filteredData.length / itemsPerPage);
                const startIndex = (currentPage - 1) * itemsPerPage;
                const endIndex = Math.min(startIndex + itemsPerPage, filteredData.length);
                const paginatedData = filteredData.slice(startIndex, endIndex);

                // Render table rows
                officeHeadTableBody.innerHTML = paginatedData.map((oh, index) => {
                    const globalIndex = startIndex + index + 1;
                    return `
                        <tr>
                            <td>${globalIndex}</td>
                            <td>${oh.name}</td>
                            <td>${oh.email}</td>
                            <td>${oh.office || '-'}</td>
                            <td>${oh.contact || '-'}</td>
                            <td>
                                <span class="badge ${oh.active ? 'bg-success' : 'bg-danger'} text-white rounded p-1 whitespace-nowrap">
                                    ${oh.active ? 'Active' : 'Inactive'}
                                </span>
                            </td>
                            <td>
                                <button class="btn btn-primary btn-sm text-white" onclick="viewOfficeHead(${oh.id})">
                                    <i data-lucide="eye" class="w-4 h-4 mr-1"></i>
                                    View
                                </button>
                            </td>
                        </tr>
                    `;
                }).join('');

                // Update pagination info
                document.getElementById('paginationStart').textContent = filteredData.length > 0 ? startIndex + 1 : 0;
                document.getElementById('paginationEnd').textContent = endIndex;
                document.getElementById('paginationTotal').textContent = filteredData.length;

                // Render pagination controls
                renderPagination(totalPages);
                
                // Show pagination container
                document.getElementById('paginationContainer').style.display = 'flex';
                
                reloadLucideIcons();
            }

            // Render pagination controls
            function renderPagination(totalPages) {
                const paginationEl = document.getElementById('pagination');
                
                if (totalPages <= 1) {
                    paginationEl.innerHTML = '';
                    document.getElementById('paginationContainer').style.display = 'none';
                    return;
                }

                let paginationHTML = '';

                // First page button
                paginationHTML += `
                    <li class="page-item ${currentPage === 1 ? 'disabled' : ''}">
                        <a class="page-link" href="#" onclick="goToPage(1); return false;">
                            <i class="w-4 h-4" data-lucide="chevrons-left"></i>
                        </a>
                    </li>
                `;

                // Previous page button
                paginationHTML += `
                    <li class="page-item ${currentPage === 1 ? 'disabled' : ''}">
                        <a class="page-link" href="#" onclick="goToPage(${currentPage - 1}); return false;">
                            <i class="w-4 h-4" data-lucide="chevron-left"></i>
                        </a>
                    </li>
                `;

                // Page numbers
                let startPage = Math.max(1, currentPage - 2);
                let endPage = Math.min(totalPages, currentPage + 2);

                if (startPage > 1) {
                    paginationHTML += `<li class="page-item"><a class="page-link" href="#" onclick="goToPage(1); return false;">1</a></li>`;
                    if (startPage > 2) {
                        paginationHTML += `<li class="page-item"><a class="page-link" href="#">...</a></li>`;
                    }
                }

                for (let i = startPage; i <= endPage; i++) {
                    paginationHTML += `
                        <li class="page-item ${i === currentPage ? 'active' : ''}">
                            <a class="page-link" href="#" onclick="goToPage(${i}); return false;">${i}</a>
                        </li>
                    `;
                }

                if (endPage < totalPages) {
                    if (endPage < totalPages - 1) {
                        paginationHTML += `<li class="page-item"><a class="page-link" href="#">...</a></li>`;
                    }
                    paginationHTML += `<li class="page-item"><a class="page-link" href="#" onclick="goToPage(${totalPages}); return false;">${totalPages}</a></li>`;
                }

                // Next page button
                paginationHTML += `
                    <li class="page-item ${currentPage === totalPages ? 'disabled' : ''}">
                        <a class="page-link" href="#" onclick="goToPage(${currentPage + 1}); return false;">
                            <i class="w-4 h-4" data-lucide="chevron-right"></i>
                        </a>
                    </li>
                `;

                // Last page button
                paginationHTML += `
                    <li class="page-item ${currentPage === totalPages ? 'disabled' : ''}">
                        <a class="page-link" href="#" onclick="goToPage(${totalPages}); return false;">
                            <i class="w-4 h-4" data-lucide="chevrons-right"></i>
                        </a>
                    </li>
                `;

                paginationEl.innerHTML = paginationHTML;
                reloadLucideIcons();
            }

            // Go to specific page
            window.goToPage = function(page) {
                const totalPages = Math.ceil(filteredData.length / itemsPerPage);
                if (page < 1 || page > totalPages || page === currentPage) {
                    return;
                }
                currentPage = page;
                renderTable();
                // Scroll to top of table
                document.querySelector('.table').scrollIntoView({ behavior: 'smooth', block: 'start' });
            };

            // Update total count
            function updateTotalCount() {
                totalCount.textContent = officeHeadsData.length;
            }

            // Toggle form
            function toggleForm() {
                if (addForm.style.display === 'none') {
                    showForm();
                } else {
                    hideForm();
                }
            }

            // Show form
            function showForm() {
                addForm.style.display = 'block';
                toggleFormBtn.innerHTML = '<i data-lucide="x" class="w-4 h-4 mr-2"></i>Hide Form';
                reloadLucideIcons();
                addForm.scrollIntoView({ behavior: 'smooth' });
                // Update office select when showing form (to refresh available offices)
                updateOfficeSelect();
            }

            // Hide form
            function hideForm() {
                addForm.style.display = 'none';
                toggleFormBtn.innerHTML = '<i data-lucide="plus" class="w-4 h-4 mr-2"></i>Add Office Head';
                reloadLucideIcons();
                officeHeadForm.reset();
                messageDiv.innerHTML = '';
                // Don't clear currentOfficeHeadId here - only clear after successful save
                if (!isEditMode) {
                    currentOfficeHeadId = null;
                }
                document.getElementById('password').required = true;
                // Update office select when hiding form (to refresh available offices)
                updateOfficeSelect();
            }

            // Handle form submission
            async function handleFormSubmit(e) {
                e.preventDefault();
                
                // Validate edit mode
                if (isEditMode && !currentOfficeHeadId) {
                    showMessage('Error: Office head ID is missing. Please try again.', 'error');
                    return;
                }
                
                const formData = new FormData(officeHeadForm);
                const data = {
                    name: formData.get('name'),
                    full_name: formData.get('full_name'),
                    email: formData.get('email'),
                    password: formData.get('password') || null,
                    office: formData.get('office'),
                    contact: formData.get('contact') || null,
                    gender: formData.get('gender'),
                    active: formData.get('active') === '1'
                };
                
                // Don't send password if it's empty in edit mode
                if (isEditMode && !data.password) {
                    delete data.password;
                }
                
                try {
                    const url = isEditMode ? `/api/officeheads/${currentOfficeHeadId}` : '/api/officeheads';
                    const method = isEditMode ? 'PUT' : 'POST';
                    
                    const response = await fetch(url, {
                        method: method,
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
                        },
                        body: JSON.stringify(data)
                    });
                    
                    const result = await response.json();
                    
                    if (response.ok) {
                        await loadOfficeHeads();
                        // Clear edit mode and ID only after successful save
                        const wasEditMode = isEditMode;
                        isEditMode = false;
                        currentOfficeHeadId = null;
                        hideForm();
                        closeOfficeHeadPanel();
                        showMessage(result.message || (wasEditMode ? 'Office head updated successfully!' : 'Office head created successfully!'), 'success');
                    } else {
                        const errorMessage = result.message || (result.errors ? Object.values(result.errors).flat().join(', ') : 'Failed to save office head');
                        showMessage(errorMessage, 'error');
                    }
                } catch (error) {
                    console.error('Error saving office head:', error);
                    showMessage('An error occurred while saving office head', 'error');
                }
            }

            // View office head
            window.viewOfficeHead = function(id) {
                const oh = officeHeadsData.find(o => o.id === id);
                if (!oh) return;

                currentOfficeHeadId = id;
                
                document.getElementById('detailName').textContent = oh.name;
                document.getElementById('detailFullName').textContent = oh.full_name;
                document.getElementById('detailEmail').textContent = oh.email;
                document.getElementById('detailOffice').textContent = oh.office || '-';
                document.getElementById('detailContact').textContent = oh.contact || '-';
                document.getElementById('detailGender').textContent = oh.gender || '-';
                document.getElementById('detailStatus').innerHTML = `<span class="badge ${oh.active ? 'bg-success' : 'bg-danger'} text-white rounded p-1">${oh.active ? 'Active' : 'Inactive'}</span>`;

                reloadLucideIcons();
                officeHeadDetailsPanel.style.display = 'block';
                officeHeadDetailsPanel.scrollIntoView({ behavior: 'smooth' });
            };

            // Close panel
            window.closeOfficeHeadPanel = function() {
                officeHeadDetailsPanel.style.display = 'none';
                // Don't clear currentOfficeHeadId if we're in edit mode
                if (!isEditMode) {
                    currentOfficeHeadId = null;
                }
            };

            // Edit office head
            window.editOfficeHead = async function() {
                if (!currentOfficeHeadId) {
                    showMessage('Error: Office head ID is missing. Please view the office head first.', 'error');
                    return;
                }
                
                // Preserve the ID before making the request
                const officeHeadIdToEdit = currentOfficeHeadId;
                
                try {
                    const response = await fetch(`/api/officeheads/${officeHeadIdToEdit}`);
                    const result = await response.json();
                    
                    if (result.success) {
                        const oh = result.data;
                        
                        // Ensure currentOfficeHeadId is set
                        currentOfficeHeadId = officeHeadIdToEdit;
                        
                        document.getElementById('name').value = oh.name || '';
                        document.getElementById('full_name').value = oh.full_name || '';
                        document.getElementById('email').value = oh.email || '';
                        document.getElementById('password').value = '';
                        document.getElementById('password').required = false;
                        document.getElementById('password').placeholder = 'Leave blank to keep current password';
                        
                        // Set office value - wait for options to load if needed
                        setTimeout(() => {
                            const officeSelect = document.getElementById('office');
                            const officeValue = oh.office || '';
                            if (officeValue) {
                                // Check if the office exists in the dropdown
                                const optionExists = Array.from(officeSelect.options).some(opt => opt.value === officeValue);
                                if (optionExists) {
                                    officeSelect.value = officeValue;
                                } else {
                                    // Office not in dropdown, show warning
                                    showMessage(`Warning: Office "${officeValue}" is not in the active offices list.`, 'warning');
                                }
                            }
                        }, 100);
                        
                        document.getElementById('contact').value = oh.contact || '';
                        document.getElementById('gender').value = oh.gender || '';
                        document.getElementById('active').value = oh.active ? '1' : '0';
                        
                        isEditMode = true;
                        showForm();
                        closeOfficeHeadPanel();
                    } else {
                        showMessage('Failed to load office head data', 'error');
                    }
                } catch (error) {
                    console.error('Error loading office head:', error);
                    showMessage('An error occurred while loading office head data', 'error');
                }
            };

            // Delete office head
            window.deleteOfficeHead = async function() {
                if (!currentOfficeHeadId) return;
                
                if (!confirm('Are you sure you want to delete this office head account? This action cannot be undone.')) {
                    return;
                }
                
                try {
                    const response = await fetch(`/api/officeheads/${currentOfficeHeadId}`, {
                        method: 'DELETE',
                        headers: {
                            'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
                        }
                    });
                    
                    const result = await response.json();
                    
                    if (response.ok) {
                        await loadOfficeHeads();
                        closeOfficeHeadPanel();
                        showMessage(result.message || 'Office head deleted successfully!', 'success');
                    } else {
                        showMessage(result.message || 'Failed to delete office head', 'error');
                    }
                } catch (error) {
                    console.error('Error deleting office head:', error);
                    showMessage('An error occurred while deleting office head', 'error');
                }
            };

            // Show message
            function showMessage(message, type) {
                messageDiv.innerHTML = `
                    <div class="alert alert-${type === 'success' ? 'success' : type === 'error' ? 'danger' : 'info'} flex items-center">
                        <i data-lucide="${type === 'success' ? 'check-circle' : type === 'error' ? 'alert-circle' : 'info'}" class="w-4 h-4 mr-2"></i>
                        ${message}
                    </div>
                `;
                
                reloadLucideIcons();
                
                setTimeout(() => {
                    messageDiv.innerHTML = '';
                }, 5000);
            }

            // Initialize
            document.addEventListener('DOMContentLoaded', init);
        })();
    </script>
@endsection

