@extends('../layout/' . $layout)

@section('subhead')
    <title>Student Assistant Account & Profile Management - SAMS</title>
@endsection

@section('subcontent')
    <div class="grid grid-cols-12 gap-6">
        <div class="col-span-12 2xl:col-span-12">
            <div class="grid grid-cols-12 gap-6">
                <!-- Header -->
                <div class="col-span-12 mt-4">
                    <div class="intro-y box p-5">
                        <h1 class="text-xl md:text-2xl font-medium flex items-center">
                            <i data-lucide="users" class="w-5 h-5 mr-2"></i>
                            Student Assistant Account & Profile Management
                        </h1>
                        <p class="text-slate-500 mt-2">Manage student assistant accounts, profiles, and assignments.</p>
                        <div class="alert alert-info mt-3 flex items-center">
                            <i data-lucide="info" class="w-4 h-4 mr-2"></i>
                            <span class="font-medium">Total Student Assistants:</span>
                            <span class="ml-2" id="totalCount">0</span>
                        </div>
                    </div>
                </div>

                <!-- Filters -->
                <div class="col-span-12 intro-y">
                    <div class="box p-5">
                        <h2 class="text-lg font-medium mb-4 flex items-center">
                            <i data-lucide="filter" class="w-5 h-5 mr-2"></i>
                            Filters
                        </h2>
                        <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
                            <div>
                                <label for="searchInput" class="form-label">Search:</label>
                                <input type="text" id="searchInput" class="form-control" placeholder="Search by name, ID, or email" />
                            </div>
                            <div>
                                <label for="officeFilter" class="form-label">Office:</label>
                                <select id="officeFilter" class="form-control">
                                    <option value="">All Offices</option>
                                </select>
                            </div>
                            <div>
                                <label for="statusFilter" class="form-label">Status:</label>
                                <select id="statusFilter" class="form-control">
                                    <option value="">All Status</option>
                                    <option value="active">Active</option>
                                    <option value="inactive">Inactive</option>
                                    <option value="apprentice">Apprentice</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- SA Accounts Table -->
                <div class="col-span-12 intro-y">
                    <div class="box p-5">
                        <h2 class="text-lg font-medium mb-4 flex items-center">
                            <i data-lucide="clipboard-list" class="w-5 h-5 mr-2"></i>
                            Student Assistant Accounts
                        </h2>
                        <div class="overflow-x-auto">
                            <table class="table table-report">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Name</th>
                                        <th>Student ID</th>
                                        <th>Email</th>
                                        <th>Office</th>
                                        <th>Contact</th>
                                        <th>Status</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody id="saTableBody">
                                    <tr>
                                        <td colspan="8" class="text-center text-slate-500">Loading...</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <!-- Pagination -->
                        <div class="intro-y flex flex-wrap sm:flex-row sm:flex-nowrap items-center mt-3" id="paginationContainer" style="display: none;">
                            <nav class="w-full sm:w-auto sm:mr-auto">
                                <ul class="pagination" id="pagination">
                                    <!-- Pagination items will be generated by JavaScript -->
                                </ul>
                            </nav>
                            <div class="hidden md:block text-slate-500">
                                Showing <span id="paginationStart">0</span> to <span id="paginationEnd">0</span> of <span id="paginationTotal">0</span> entries
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Add SA Section -->
                <div class="col-span-12 intro-y">
                    <div class="box p-5">
                        <div class="flex items-center justify-between mb-4">
                            <h2 class="text-lg font-medium flex items-center mr-auto">
                                <i data-lucide="user-plus" class="w-5 h-5 mr-2"></i>
                                Add New Student Assistant
                            </h2>
                        </div>
                        
                        <div class="add-form" id="addForm" style="display: none;">
                            <form id="saForm" class="grid grid-cols-12 gap-4">
                                <div class="col-span-12 md:col-span-6">
                                    <label for="name" class="form-label">Name: <span class="text-danger">*</span></label>
                                    <input type="text" id="name" name="name" class="form-control" required />
                                </div>
                                <div class="col-span-12 md:col-span-6">
                                    <label for="full_name" class="form-label">Full Name: <span class="text-danger">*</span></label>
                                    <input type="text" id="full_name" name="full_name" class="form-control" required />
                                </div>
                                <div class="col-span-12 md:col-span-6">
                                    <label for="student_id_number" class="form-label">Student ID Number: <span class="text-danger">*</span></label>
                                    <input type="text" id="student_id_number" name="student_id_number" class="form-control" required />
                                </div>
                                <div class="col-span-12 md:col-span-6">
                                    <label for="email" class="form-label">Email: <span class="text-danger">*</span></label>
                                    <input type="email" id="email" name="email" class="form-control" required />
                                </div>
                                <div class="col-span-12 md:col-span-6">
                                    <label for="password" class="form-label">Password: <span class="text-danger">*</span></label>
                                    <input type="password" id="password" name="password" class="form-control" required minlength="8" />
                                </div>
                                <div class="col-span-12 md:col-span-6">
                                    <label for="office" class="form-label">Office: <span class="text-danger">*</span></label>
                                    <select id="office" name="office" class="form-control" required>
                                        <option value="">Select Office</option>
                                    </select>
                                </div>
                                <div class="col-span-12 md:col-span-6">
                                    <label for="contact" class="form-label">Contact Number:</label>
                                    <input type="text" id="contact" name="contact" class="form-control" placeholder="09XXXXXXXXX" pattern="^09\d{9}$" />
                                </div>
                                <div class="col-span-12 md:col-span-6">
                                    <label for="gender" class="form-label">Gender: <span class="text-danger">*</span></label>
                                    <select id="gender" name="gender" class="form-control" required>
                                        <option value="">Select Gender</option>
                                        <option value="male">Male</option>
                                        <option value="female">Female</option>
                                        <option value="other">Other</option>
                                    </select>
                                </div>
                                <div class="col-span-12 md:col-span-6">
                                    <label for="status" class="form-label">Status:</label>
                                    <select id="status" name="status" class="form-control">
                                        <option value="Active">Active</option>
                                        <option value="Inactive">Inactive</option>
                                        <option value="Apprentice">Apprentice</option>
                                        <option value="Pending Assignment">Pending Assignment</option>
                                    </select>
                                </div>
                                <input type="hidden" id="active" name="active" value="1">
                                <div class="col-span-12 md:col-span-6">
                                    <label for="contract_start_date" class="form-label">Contract Start Date (First Day of Work):</label>
                                    <input type="date" id="contract_start_date" name="contract_start_date" class="form-control" />
                                </div>
                                <div class="col-span-12 md:col-span-6">
                                    <label for="contract_end_date" class="form-label">Contract End Date (Last Day of Work):</label>
                                    <input type="date" id="contract_end_date" name="contract_end_date" class="form-control" />
                                </div>
                                <!-- Scheduled Time Section -->
                                <div class="col-span-12 mt-4">
                                    <h3 class="text-base font-medium mb-3 flex items-center">
                                        <i data-lucide="clock" class="w-4 h-4 mr-2"></i>
                                        Scheduled Work Time
                                    </h3>
                                    <div class="grid grid-cols-12 gap-4">
                                        <!-- Simple Schedule (Single Time In/Out) -->
                                        <div class="col-span-12 md:col-span-6">
                                            <label for="scheduled_time_in" class="form-label">Scheduled Time In:</label>
                                            <input type="time" id="scheduled_time_in" name="scheduled_time_in" class="form-control" />
                                            <small class="text-slate-500">Default time in for regular schedule</small>
                                        </div>
                                        <div class="col-span-12 md:col-span-6">
                                            <label for="scheduled_time_out" class="form-label">Scheduled Time Out:</label>
                                            <input type="time" id="scheduled_time_out" name="scheduled_time_out" class="form-control" />
                                            <small class="text-slate-500">Default time out for regular schedule</small>
                                        </div>
                                        <!-- Broken Schedule (Multiple Time Slots) -->
                                        <div class="col-span-12">
                                            <label class="form-label">Work Schedule (For Broken Schedules):</label>
                                            <div id="scheduleSlotsContainer" class="space-y-3">
                                                <!-- Schedule slots will be added here -->
                                            </div>
                                            <button type="button" id="addScheduleSlotBtn" class="btn btn-sm btn-outline-primary mt-2">
                                                <i data-lucide="plus" class="w-4 h-4 mr-1"></i>
                                                Add Time Slot
                                            </button>
                                            <small class="block text-slate-500 mt-1">Add multiple time slots for broken schedules (e.g., 8:00 AM - 12:00 PM, 1:00 PM - 5:00 PM)</small>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-span-12">
                                    <button type="submit" class="btn btn-primary">
                                        <i data-lucide="save" class="w-4 h-4 mr-2"></i>
                                        Save Student Assistant
                                    </button>
                                    <button type="button" id="cancelFormBtn" class="btn btn-secondary ml-2">
                                        <i data-lucide="x" class="w-4 h-4 mr-2 text-black"></i>
                                        Cancel
                                    </button>
                                </div>
                            </form>
                        </div>
                        <div id="message" class="mt-3"></div>
                    </div>
                </div>

                <!-- SA Details Panel -->
                <div class="col-span-12 intro-y" id="saDetailsPanel" style="display: none;">
                    <div class="box p-5">
                        <h2 class="text-lg font-medium mb-4 flex items-center">
                            <i data-lucide="user" class="w-5 h-5 mr-2"></i>
                            Student Assistant Details
                        </h2>
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                            <div>
                                <span class="font-medium text-slate-600">Nickname:</span>
                                <span id="detailName" class="text-slate-800"></span>
                            </div>
                            <div>
                                <span class="font-medium text-slate-600">Full Name:</span>
                                <span id="detailFullName" class="text-slate-800"></span>
                            </div>
                            <div>
                                <span class="font-medium text-slate-600">Student ID:</span>
                                <span id="detailStudentId" class="text-slate-800"></span>
                            </div>
                            <div>
                                <span class="font-medium text-slate-600">Email:</span>
                                <span id="detailEmail" class="text-slate-800"></span>
                            </div>
                            <div>
                                <span class="font-medium text-slate-600">Office:</span>
                                <span id="detailOffice" class="text-slate-800"></span>
                            </div>
                            <div>
                                <span class="font-medium text-slate-600">Contact:</span>
                                <span id="detailContact" class="text-slate-800"></span>
                            </div>
                            <div>
                                <span class="font-medium text-slate-600">Gender:</span>
                                <span id="detailGender" class="text-slate-800"></span>
                            </div>
                            <div>
                                <span class="font-medium text-slate-600">Status:</span>
                                <span id="detailStatus" class="text-slate-800"></span>
                            </div>
                            <div>
                                <span class="font-medium text-slate-600">Contract Start Date (First Day):</span>
                                <span id="detailContractStart" class="text-slate-800"></span>
                            </div>
                            <div>
                                <span class="font-medium text-slate-600">Contract End Date (Last Day):</span>
                                <span id="detailContractEnd" class="text-slate-800"></span>
                            </div>
                        </div>
                        <div class="flex gap-2">
                            <button class="btn btn-primary" onclick="editSA()">
                                <i data-lucide="edit" class="w-4 h-4 mr-2"></i>
                                Edit
                            </button>
                            <button class="btn btn-danger" onclick="deleteSA()">
                                <i data-lucide="trash-2" class="w-4 h-4 mr-2"></i>
                                Delete
                            </button>
                            <button class="btn btn-secondary" onclick="closeSAPanel()">
                                <i data-lucide="x" class="w-4 h-4 mr-2"></i>
                                Close
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script type="module">
        (function () {
            let saData = [];
            let filteredData = [];
            let officesData = [];
            let currentSAId = null;
            let isEditMode = false;
            
            // Pagination variables
            let currentPage = 1;
            const itemsPerPage = 10;

            // DOM elements
            const searchInput = document.getElementById('searchInput');
            const officeFilter = document.getElementById('officeFilter');
            const statusFilter = document.getElementById('statusFilter');
            const saTableBody = document.getElementById('saTableBody');
            const addForm = document.getElementById('addForm');
            const toggleFormBtn = document.getElementById('toggleFormBtn');
            const cancelFormBtn = document.getElementById('cancelFormBtn');
            const saForm = document.getElementById('saForm');
            const saDetailsPanel = document.getElementById('saDetailsPanel');
            const totalCount = document.getElementById('totalCount');
            const messageDiv = document.getElementById('message');
            const officeSelect = document.getElementById('office');

            // Helper function to get status badge class
            function getStatusBadgeClass(status) {
                switch(status) {
                    case 'Active':
                        return 'bg-success';
                    case 'Inactive':
                        return 'bg-danger';
                    case 'Apprentice':
                        return 'bg-warning';
                    case 'Pending Assignment':
                        return 'bg-info';
                    default:
                        return 'bg-secondary';
                }
            }

            // Helper function to re-initialize Lucide icons
            function reloadLucideIcons() {
                if (window.lucide && window.lucide.createIcons) {
                    window.lucide.createIcons({
                        icons: window.lucide.icons,
                        "stroke-width": 1.5,
                        nameAttr: "data-lucide",
                    });
                }
            }

            // Initialize page
            async function init() {
                await Promise.all([loadOffices(), loadSAAccounts()]);
                setupEventListeners();
            }

            // Load offices for dropdown
            async function loadOffices() {
                try {
                    const response = await fetch('/api/offices');
                    const result = await response.json();
                    
                    if (result.success) {
                        officesData = result.data.filter(o => o.is_active);
                        officeSelect.innerHTML = '<option value="">Select Office</option>' + 
                            officesData.map(office => `<option value="${office.name}">${office.name}</option>`).join('');
                        
                        // Populate office filter
                        officeFilter.innerHTML = '<option value="">All Offices</option>' + 
                            officesData.map(office => `<option value="${office.name}">${office.name}</option>`).join('');
                    }
                } catch (error) {
                    console.error('Error loading offices:', error);
                }
            }

            // Load SA accounts from API
            async function loadSAAccounts() {
                try {
                    const response = await fetch('/api/sa-accounts');
                    const result = await response.json();
                    
                    if (result.success) {
                        saData = result.data;
                        filteredData = [...saData];
                        updateTotalCount();
                        renderTable();
                    } else {
                        showMessage('Failed to load student assistants', 'error');
                    }
                } catch (error) {
                    console.error('Error loading student assistants:', error);
                    showMessage('An error occurred while loading student assistants', 'error');
                    saTableBody.innerHTML = '<tr><td colspan="8" class="text-center text-slate-500">Error loading student assistants</td></tr>';
                }
            }

            // Schedule slots management
            let scheduleSlotCounter = 0;
            
            // Add schedule slot
            function addScheduleSlot(timeIn = '', timeOut = '') {
                const container = document.getElementById('scheduleSlotsContainer');
                const slotId = `scheduleSlot_${scheduleSlotCounter++}`;
                
                const slotHTML = `
                    <div class="schedule-slot flex items-center gap-2 p-3 border rounded" data-slot-id="${slotId}">
                        <div class="flex-1">
                            <label class="form-label text-xs">Time In:</label>
                            <input type="time" class="form-control form-control-sm schedule-time-in" value="${timeIn}" />
                        </div>
                        <div class="flex-1">
                            <label class="form-label text-xs">Time Out:</label>
                            <input type="time" class="form-control form-control-sm schedule-time-out" value="${timeOut}" />
                        </div>
                        <button type="button" class="btn btn-sm btn-outline-danger remove-slot-btn" onclick="removeScheduleSlot('${slotId}')">
                            <i data-lucide="trash-2" class="w-4 h-4"></i>
                        </button>
                    </div>
                `;
                
                container.insertAdjacentHTML('beforeend', slotHTML);
                reloadLucideIcons();
            }
            
            // Remove schedule slot
            window.removeScheduleSlot = function(slotId) {
                const slot = document.querySelector(`[data-slot-id="${slotId}"]`);
                if (slot) {
                    slot.remove();
                }
            };
            
            // Get all schedule slots
            function getScheduleSlots() {
                const slots = [];
                const slotElements = document.querySelectorAll('.schedule-slot');
                
                slotElements.forEach(slot => {
                    const timeIn = slot.querySelector('.schedule-time-in').value;
                    const timeOut = slot.querySelector('.schedule-time-out').value;
                    
                    if (timeIn && timeOut) {
                        slots.push({
                            time_in: timeIn,
                            time_out: timeOut
                        });
                    }
                });
                
                return slots;
            }
            
            // Clear schedule slots
            function clearScheduleSlots() {
                const container = document.getElementById('scheduleSlotsContainer');
                container.innerHTML = '';
                scheduleSlotCounter = 0;
            }

            // Setup event listeners
            function setupEventListeners() {
                searchInput.addEventListener('input', filterData);
                officeFilter.addEventListener('change', filterData);
                statusFilter.addEventListener('change', filterData);
                toggleFormBtn.addEventListener('click', toggleForm);
                cancelFormBtn.addEventListener('click', hideForm);
                saForm.addEventListener('submit', handleFormSubmit);
                
                // Add schedule slot button
                const addScheduleSlotBtn = document.getElementById('addScheduleSlotBtn');
                if (addScheduleSlotBtn) {
                    addScheduleSlotBtn.addEventListener('click', () => addScheduleSlot());
                }
                
                // Validate contract end date is after start date (only if both dates are provided)
                const contractStartDate = document.getElementById('contract_start_date');
                const contractEndDate = document.getElementById('contract_end_date');
                
                contractStartDate.addEventListener('change', function() {
                    if (this.value && contractEndDate.value && contractEndDate.value <= this.value) {
                        contractEndDate.setCustomValidity('Contract end date must be after start date');
                    } else {
                        contractEndDate.setCustomValidity('');
                    }
                });
                
                contractEndDate.addEventListener('change', function() {
                    if (this.value && contractStartDate.value && this.value <= contractStartDate.value) {
                        this.setCustomValidity('Contract end date must be after start date');
                    } else {
                        this.setCustomValidity('');
                    }
                });
            }

            // Filter data
            function filterData() {
                const searchTerm = searchInput.value.toLowerCase();
                const selectedOffice = officeFilter.value;
                const selectedStatus = statusFilter.value;

                filteredData = saData.filter(sa => {
                    const matchesSearch = !searchTerm || 
                        sa.name.toLowerCase().includes(searchTerm) || 
                        (sa.student_id_number && sa.student_id_number.toLowerCase().includes(searchTerm)) ||
                        sa.email.toLowerCase().includes(searchTerm);
                    
                    const matchesOffice = !selectedOffice || sa.office === selectedOffice;
                    
                    const matchesStatus = !selectedStatus || 
                        (selectedStatus === 'active' && (sa.active || sa.status === 'Active')) ||
                        (selectedStatus === 'inactive' && (!sa.active || sa.status === 'Inactive')) ||
                        (selectedStatus === 'apprentice' && sa.status === 'Apprentice');

                    return matchesSearch && matchesOffice && matchesStatus;
                });

                // Reset to first page when filtering
                currentPage = 1;
                renderTable();
            }

            // Render table with pagination
            function renderTable() {
                if (filteredData.length === 0) {
                    saTableBody.innerHTML = '<tr><td colspan="8" class="text-center text-slate-500">No student assistants found</td></tr>';
                    document.getElementById('paginationContainer').style.display = 'none';
                    return;
                }

                // Calculate pagination
                const totalPages = Math.ceil(filteredData.length / itemsPerPage);
                const startIndex = (currentPage - 1) * itemsPerPage;
                const endIndex = Math.min(startIndex + itemsPerPage, filteredData.length);
                const paginatedData = filteredData.slice(startIndex, endIndex);

                // Render table rows
                saTableBody.innerHTML = paginatedData.map((sa, index) => {
                    const globalIndex = startIndex + index + 1;
                    return `
                        <tr>
                            <td>${globalIndex}</td>
                            <td>${sa.name}</td>
                            <td>${sa.student_id_number || '-'}</td>
                            <td>${sa.email}</td>
                            <td>${sa.office || '-'}</td>
                            <td>${sa.contact || '-'}</td>
                            <td>
                                <span class="badge ${getStatusBadgeClass(sa.status || (sa.active ? 'Active' : 'Inactive'))} text-white rounded p-1 whitespace-nowrap">
                                    ${sa.status || (sa.active ? 'Active' : 'Inactive')}
                                </span>
                            </td>
                            <td>
                                <button class="btn btn-primary btn-sm text-white" onclick="viewSA(${sa.id})">
                                    <i data-lucide="eye" class="w-4 h-4 mr-1"></i>
                                    View
                                </button>
                            </td>
                        </tr>
                    `;
                }).join('');

                // Update pagination info
                document.getElementById('paginationStart').textContent = filteredData.length > 0 ? startIndex + 1 : 0;
                document.getElementById('paginationEnd').textContent = endIndex;
                document.getElementById('paginationTotal').textContent = filteredData.length;

                // Render pagination
                renderPagination(totalPages);
                
                // Show pagination container
                document.getElementById('paginationContainer').style.display = 'flex';
                
                reloadLucideIcons();
            }

            // Render pagination controls
            function renderPagination(totalPages) {
                const paginationEl = document.getElementById('pagination');
                
                if (totalPages <= 1) {
                    paginationEl.innerHTML = '';
                    document.getElementById('paginationContainer').style.display = 'none';
                    return;
                }

                let paginationHTML = '';

                // First page button
                paginationHTML += `
                    <li class="page-item ${currentPage === 1 ? 'disabled' : ''}">
                        <a class="page-link" href="#" onclick="goToPage(1); return false;">
                            <i class="w-4 h-4" data-lucide="chevrons-left"></i>
                        </a>
                    </li>
                `;

                // Previous page button
                paginationHTML += `
                    <li class="page-item ${currentPage === 1 ? 'disabled' : ''}">
                        <a class="page-link" href="#" onclick="goToPage(${currentPage - 1}); return false;">
                            <i class="w-4 h-4" data-lucide="chevron-left"></i>
                        </a>
                    </li>
                `;

                // Page numbers
                let startPage = Math.max(1, currentPage - 2);
                let endPage = Math.min(totalPages, currentPage + 2);

                if (startPage > 1) {
                    paginationHTML += `<li class="page-item"><a class="page-link" href="#" onclick="goToPage(1); return false;">1</a></li>`;
                    if (startPage > 2) {
                        paginationHTML += `<li class="page-item"><a class="page-link" href="#">...</a></li>`;
                    }
                }

                for (let i = startPage; i <= endPage; i++) {
                    paginationHTML += `
                        <li class="page-item ${i === currentPage ? 'active' : ''}">
                            <a class="page-link" href="#" onclick="goToPage(${i}); return false;">${i}</a>
                        </li>
                    `;
                }

                if (endPage < totalPages) {
                    if (endPage < totalPages - 1) {
                        paginationHTML += `<li class="page-item"><a class="page-link" href="#">...</a></li>`;
                    }
                    paginationHTML += `<li class="page-item"><a class="page-link" href="#" onclick="goToPage(${totalPages}); return false;">${totalPages}</a></li>`;
                }

                // Next page button
                paginationHTML += `
                    <li class="page-item ${currentPage === totalPages ? 'disabled' : ''}">
                        <a class="page-link" href="#" onclick="goToPage(${currentPage + 1}); return false;">
                            <i class="w-4 h-4" data-lucide="chevron-right"></i>
                        </a>
                    </li>
                `;

                // Last page button
                paginationHTML += `
                    <li class="page-item ${currentPage === totalPages ? 'disabled' : ''}">
                        <a class="page-link" href="#" onclick="goToPage(${totalPages}); return false;">
                            <i class="w-4 h-4" data-lucide="chevrons-right"></i>
                        </a>
                    </li>
                `;

                paginationEl.innerHTML = paginationHTML;
                reloadLucideIcons();
            }

            // Go to specific page
            window.goToPage = function(page) {
                const totalPages = Math.ceil(filteredData.length / itemsPerPage);
                if (page < 1 || page > totalPages || page === currentPage) {
                    return;
                }
                currentPage = page;
                renderTable();
                // Scroll to top of table
                document.querySelector('.table').scrollIntoView({ behavior: 'smooth', block: 'start' });
            };

            // Update total count
            function updateTotalCount() {
                totalCount.textContent = saData.length;
            }

            // Toggle form
            function toggleForm() {
                if (addForm.style.display === 'none') {
                    showForm();
                } else {
                    hideForm();
                }
            }

            // Show form
            function showForm() {
                addForm.style.display = 'block';
                toggleFormBtn.innerHTML = '<i data-lucide="x" class="w-4 h-4 mr-2"></i>Hide Form';
                reloadLucideIcons();
                addForm.scrollIntoView({ behavior: 'smooth' });
            }

            // Hide form
            function hideForm() {
                addForm.style.display = 'none';
                toggleFormBtn.innerHTML = '<i data-lucide="plus" class="w-4 h-4 mr-2"></i>Add Student Assistant';
                reloadLucideIcons();
                saForm.reset();
                clearScheduleSlots();
                messageDiv.innerHTML = '';
                isEditMode = false;
                // Don't clear currentSAId here if we're in edit mode - only clear it after successful save
                const passwordField = document.getElementById('password');
                passwordField.required = true;
                passwordField.placeholder = '';
            }

            // Handle form submission
            async function handleFormSubmit(e) {
                e.preventDefault();
                
                // Validate that currentSAId is set if in edit mode
                if (isEditMode && !currentSAId) {
                    showMessage('Error: Student Assistant ID is missing. Please try again.', 'error');
                    console.error('Edit mode is true but currentSAId is null');
                    return;
                }
                
                const formData = new FormData(saForm);
                const status = formData.get('status') || 'Active';
                
                // Get schedule slots
                const scheduleSlots = getScheduleSlots();
                
                const data = {
                    name: formData.get('name'),
                    full_name: formData.get('full_name'),
                    student_id_number: formData.get('student_id_number'),
                    email: formData.get('email'),
                    password: formData.get('password') || null,
                    office: formData.get('office'),
                    contact: formData.get('contact') || null,
                    gender: formData.get('gender'),
                    status: status,
                    active: status === 'Active' || status === 'Apprentice' ? 1 : 0,
                    contract_start_date: formData.get('contract_start_date') || null,
                    contract_end_date: formData.get('contract_end_date') || null,
                    scheduled_time_in: formData.get('scheduled_time_in') || null,
                    scheduled_time_out: formData.get('scheduled_time_out') || null,
                    work_schedule: scheduleSlots.length > 0 ? scheduleSlots : null
                };
                
                try {
                    const url = isEditMode ? `/api/sa-accounts/${currentSAId}` : '/api/sa-accounts';
                    const method = isEditMode ? 'PUT' : 'POST';
                    
                    console.log('Submitting form:', { isEditMode, currentSAId, url, method });
                    
                    const response = await fetch(url, {
                        method: method,
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
                        },
                        body: JSON.stringify(data)
                    });
                    
                    const result = await response.json();
                    
                    if (response.ok) {
                        await loadSAAccounts();
                        // Store edit mode status before clearing
                        const wasEditMode = isEditMode;
                        // Clear edit mode and ID after successful save
                        isEditMode = false;
                        currentSAId = null;
                        hideForm();
                        closeSAPanel();
                        showMessage(result.message || (wasEditMode ? 'Student assistant updated successfully!' : 'Student assistant created successfully!'), 'success');
                    } else {
                        const errorMessage = result.message || (result.errors ? Object.values(result.errors).flat().join(', ') : 'Failed to save student assistant');
                        showMessage(errorMessage, 'error');
                    }
                } catch (error) {
                    console.error('Error saving student assistant:', error);
                    showMessage('An error occurred while saving student assistant', 'error');
                }
            }

            // View SA
            window.viewSA = function(id) {
                const sa = saData.find(s => s.id === id);
                if (!sa) return;

                currentSAId = id;
                
                document.getElementById('detailName').textContent = sa.name;
                document.getElementById('detailFullName').textContent = sa.full_name;
                document.getElementById('detailStudentId').textContent = sa.student_id_number || '-';
                document.getElementById('detailEmail').textContent = sa.email;
                document.getElementById('detailOffice').textContent = sa.office || '-';
                document.getElementById('detailContact').textContent = sa.contact || '-';
                document.getElementById('detailGender').textContent = sa.gender || '-';
                const status = sa.status || (sa.active ? 'Active' : 'Inactive');
                document.getElementById('detailStatus').innerHTML = `<span class="badge ${getStatusBadgeClass(status)} text-white rounded p-1">${status}</span>`;
                
                // Format and display contract dates
                const formatDate = (dateString) => {
                    if (!dateString) return '-';
                    const date = new Date(dateString);
                    return date.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
                };
                document.getElementById('detailContractStart').textContent = formatDate(sa.contract_start_date);
                document.getElementById('detailContractEnd').textContent = formatDate(sa.contract_end_date);

                reloadLucideIcons();
                saDetailsPanel.style.display = 'block';
                saDetailsPanel.scrollIntoView({ behavior: 'smooth' });
            };

            // Close panel
            window.closeSAPanel = function() {
                saDetailsPanel.style.display = 'none';
                // Only clear currentSAId if we're not in edit mode
                if (!isEditMode) {
                    currentSAId = null;
                }
            };

            // Edit SA
            window.editSA = async function() {
                if (!currentSAId) {
                    showMessage('No student assistant selected. Please select one first.', 'error');
                    return;
                }
                
                // Store the ID before closing panel (since closeSAPanel sets it to null)
                const saIdToEdit = currentSAId;
                
                try {
                    const response = await fetch(`/api/sa-accounts/${saIdToEdit}`);
                    const result = await response.json();
                    
                    if (result.success) {
                        const sa = result.data;
                        
                        // Populate form fields
                        document.getElementById('name').value = sa.name || '';
                        document.getElementById('full_name').value = sa.full_name || '';
                        document.getElementById('student_id_number').value = sa.student_id_number || '';
                        document.getElementById('email').value = sa.email || '';
                        
                        // Password field - set placeholder and make optional for edit
                        const passwordField = document.getElementById('password');
                        passwordField.value = '';
                        passwordField.required = false;
                        passwordField.placeholder = 'Leave blank to keep current password';
                        
                        // Office field - ensure dropdown is populated first, then set value
                        const officeSelect = document.getElementById('office');
                        if (sa.office) {
                            // Wait a bit to ensure office options are loaded, then set value
                            setTimeout(() => {
                                officeSelect.value = sa.office || '';
                                // If value still not set, try to add it as an option
                                if (!officeSelect.value && sa.office) {
                                    const option = document.createElement('option');
                                    option.value = sa.office;
                                    option.textContent = sa.office;
                                    officeSelect.appendChild(option);
                                    officeSelect.value = sa.office;
                                }
                            }, 100);
                        }
                        
                        document.getElementById('contact').value = sa.contact || '';
                        document.getElementById('gender').value = sa.gender || '';
                        // Set status field if it exists, otherwise use active
                        const statusField = document.getElementById('status');
                        if (statusField) {
                            statusField.value = sa.status || (sa.active ? 'Active' : 'Inactive');
                        } else {
                            // Fallback to active field if status field doesn't exist
                            document.getElementById('active').value = sa.active ? '1' : '0';
                        }
                        
                        // Format dates for input fields (YYYY-MM-DD)
                        const formatDateForInput = (dateString) => {
                            if (!dateString) return '';
                            const date = new Date(dateString);
                            const year = date.getFullYear();
                            const month = String(date.getMonth() + 1).padStart(2, '0');
                            const day = String(date.getDate()).padStart(2, '0');
                            return `${year}-${month}-${day}`;
                        };
                        document.getElementById('contract_start_date').value = formatDateForInput(sa.contract_start_date);
                        document.getElementById('contract_end_date').value = formatDateForInput(sa.contract_end_date);
                        
                        // Format time for input fields (HH:MM)
                        const formatTimeForInput = (timeString) => {
                            if (!timeString) return '';
                            // If time is in HH:MM:SS format, extract HH:MM
                            if (timeString.includes(':')) {
                                const parts = timeString.split(':');
                                return `${parts[0]}:${parts[1]}`;
                            }
                            return timeString;
                        };
                        document.getElementById('scheduled_time_in').value = formatTimeForInput(sa.scheduled_time_in);
                        document.getElementById('scheduled_time_out').value = formatTimeForInput(sa.scheduled_time_out);
                        
                        // Load work schedule slots
                        clearScheduleSlots();
                        if (sa.work_schedule && Array.isArray(sa.work_schedule) && sa.work_schedule.length > 0) {
                            sa.work_schedule.forEach(slot => {
                                addScheduleSlot(
                                    formatTimeForInput(slot.time_in),
                                    formatTimeForInput(slot.time_out)
                                );
                            });
                        }
                        
                        // Set edit mode and current ID BEFORE closing panel
                        isEditMode = true;
                        currentSAId = saIdToEdit; // Ensure this is set
                        
                        // Show form first
                        showForm();
                        
                        // Close panel (but don't clear currentSAId since we're in edit mode)
                        saDetailsPanel.style.display = 'none';
                        
                        // Verify currentSAId is still set
                        if (!currentSAId) {
                            currentSAId = saIdToEdit;
                            console.log('Restored currentSAId:', currentSAId);
                        }
                        
                        console.log('Edit mode set:', { isEditMode, currentSAId });
                    } else {
                        showMessage('Failed to load student assistant data', 'error');
                    }
                } catch (error) {
                    console.error('Error loading student assistant:', error);
                    showMessage('An error occurred while loading student assistant data', 'error');
                }
            };

            // Delete SA
            window.deleteSA = async function() {
                if (!currentSAId) return;
                
                if (!confirm('Are you sure you want to delete this student assistant account? This action cannot be undone.')) {
                    return;
                }
                
                try {
                    const response = await fetch(`/api/sa-accounts/${currentSAId}`, {
                        method: 'DELETE',
                        headers: {
                            'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
                        }
                    });
                    
                    const result = await response.json();
                    
                    if (response.ok) {
                        await loadSAAccounts();
                        closeSAPanel();
                        showMessage(result.message || 'Student assistant deleted successfully!', 'success');
                    } else {
                        showMessage(result.message || 'Failed to delete student assistant', 'error');
                    }
                } catch (error) {
                    console.error('Error deleting student assistant:', error);
                    showMessage('An error occurred while deleting student assistant', 'error');
                }
            };

            // Show message
            function showMessage(message, type) {
                messageDiv.innerHTML = `
                    <div class="alert alert-${type === 'success' ? 'success' : type === 'error' ? 'danger' : 'info'} flex items-center">
                        <i data-lucide="${type === 'success' ? 'check-circle' : type === 'error' ? 'alert-circle' : 'info'}" class="w-4 h-4 mr-2"></i>
                        ${message}
                    </div>
                `;
                
                reloadLucideIcons();
                
                setTimeout(() => {
                    messageDiv.innerHTML = '';
                }, 5000);
            }

            // Initialize
            document.addEventListener('DOMContentLoaded', init);
        })();
    </script>
@endsection

